source 'https://github.com/CocoaPods/Specs.git'

#  支持 iOS 8.0后的版本
platform :ios, '8.0'  

use_frameworks!

#  target "项目名" do
target "chatcoin" do      

# 	  pod 'MBProgressHUD', '~> 1.0.0'    
#    如果要同时添加多个第三方，可以添加多条 pod 语句
#    pod '第三方名称', '~> 指定版本号'

pod 'YYText'
pod 'YYImage'
pod 'FMDB'
pod 'RealReachability'

#自动导入FMDB和SQLCipher 实现数据库操作和加密
#pod 'FMDB/SQLCipher'

#对FMDB的封装，实现ORM面向对象操作数据库
pod 'LKDBHelper'

#支持内存和磁盘缓存
pod 'YYCache'

#AFNetworking 3.x
#pod 'AFNetworking', '~> 3.0'

#AFNetworking 3.x 与YYCache封装
pod 'PPNetworkHelper'

#模型转换
pod 'MJExtension'

#下拉刷新
pod 'MJRefresh'


#解决打印日志对于Unicode编码不能正常显示中文的问题
#pod 'HYBUnicodeReadable'
#//FIXME: 聊天键盘弹出时崩溃 -[_UIViewServiceViewControllerDeputyXPCInterface remoteViewControllerInterface]: unrecognized selector sent to instance 0x1742209e0

#MessageDisplayKit
#pod 'MessageDisplayKit'

end

